models/File.php
<?php

/**
 * This is the model class for table "{{files}}".
 *
 * The followings are the available columns in table '{{files}}':
 * @property integer $id
 * @property integer $filename
 * @property string $description
 * @property string $created
 * @property string $updated
 * @property integer $folder_id
 * @property integer $downloads
 * @property integer $permission
 * @property string $file_hash
 * @property integer $filesize
 * @property string $mime
 * @property string $extension
 *
 * @package File
 * @subpackage File
 */
class File extends CActiveRecord
{
	/**
	 * Uploaded data
	 */
	public $file_data;
	
	/**
	 * Save attributes for afterDelete method
	 */
	private $_oldValues = array();
	
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Files the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{file_file}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		return array(
			array('filename, file_hash, filesize, extension', 'required'),
			
			array('file_data, created', 'required', 'on' => 'create'),
			array('created', 'required', 'on' => 'upload'),
			array('updated', 'required', 'on' => 'update'),
			
			array('filesize, folder_id, downloads, permission', 'numerical', 'integerOnly' => true),
			
			array('filename', 'length', 'max' => 255),
			array('mime', 'length', 'max' => 50),
			array('extension', 'length', 'max' => 20),
			
			array('description', 'safe'),
			array('id, filename, file_hash, filesize, extension, mime, description, created, updated, folder_id, downloads, permission', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		return array(
			'theFolder' => array(self::BELONGS_TO, 'Folder', 'folder_id'),
		);
	}
	
	public function defaultScope() {
		$t = $this->getTableAlias(false, false);
		return array(
			'condition' => "$t.permission <= :permission",
			'order' => "$t.filename ASC",
			'params' => array(
				':permission' => Yii::app()->user->level,
			),
		);
	}
	
	public function afterDelete() {
		$filename = Yii::app()->basePath.'/files/'.$this->_oldValues['file_hash'];
		
		if (is_file($filename))
			unlink($filename);
		
		return parent::afterDelete();
	}
	
	public function beforeValidate() {
		if ($this->isNewRecord)
			$this->created = date('Y-m-d H:i:s');
		else
			$this->updated = date('Y-m-d H:i:s');
		
		return parent::beforeValidate();
	}
	
	public function afterFind() {
		$this->_oldValues = $this->attributes;
		
		if (empty($this->created) or ($this->created == '0000-00-00 00:00:00'))
			$this->created = '';
		
		if (empty($this->updated) or ($this->updated == '0000-00-00 00:00:00'))
			$this->updated = '';
		
		return parent::afterFind();
	}
	
	/**
	 * Get all user permissions
	 */
	public function getPermissions() {
		return Yii::app()->user->getPermissions();
	}
	
	/**
	 * Get the default permission for a new subfolder
	 */
	public function getDefaultPermission() {
		if (isset($this->theFolder->permission))
			return $this->theFolder->permission;
		elseif (isset($this->folder_id) and ($this->folder_id > 0)) {
			$folder = Folder::model()->findByPk($this->folder_id);
			
			if (is_null($folder))
				return 0;
			else
				return $folder->permission;
		}
		else
			return 0;
	}
	
	/*
	 * Generate filename
	 */
	public function generateFileName($tempName = null) {
		return md5_file($this->file_data->tempName);
	}
	
	/**
	 * Get filename with extension
	 */
	public function getFullFilename() {
		if (!empty($this->extension))
			return $this->filename.'.'.$this->extension;
	}
	
	/**
	 * Get information about the uploaded file and save them into the database
	 */
	public function prepareFile($file = array()) {
		if (empty($file)) {
			$this->filename = $this->file_data->name;
			$this->file_hash = md5_file($this->file_data->tempName);
			$this->filesize = $this->file_data->size;
			$this->extension = $this->file_data->extensionName;
			$this->mime = $this->file_data->type;
		}
		else {
			$this->filename = $file['filename'];
			$this->file_hash = $file['file_hash'];
			$this->filesize = $file['filesize'];
			$this->extension = $file['extension'];
			$this->mime = $file['mime'];
		}
	}
	
	/**
	 * Get the filesize in a human readable form
	 */
	public function getFilesizeRead() {
		if (empty($this->filesize))
			$this->filesize = 0;
		if ($this->filesize > 1024*1024*1024) {
			return round($this->filesize/1024/1024/1024, 2).' GB';
		}
		elseif ($this->filesize > 1024*1024) {
			return round($this->filesize/1024/1024, 1).' MB';
		}
		elseif ($this->filesize > 1024) {
			return round($this->filesize/1024).' KB';
		}
		else {
			return $this->filesize.' Byte';
		}
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => Yii::t('File', 'ID'),
			'filename' => Yii::t('File', 'Dateiname'),
			'file_hash' => Yii::t('File', 'Hash'),
			'filesize' => Yii::t('File', 'Dateigröße'),
			'extension' => Yii::t('File', 'Dateiendung'),
			'mime' => Yii::t('File', 'Dateityp'),
			'description' => Yii::t('File', 'Beschreibung'),
			'created' => Yii::t('File', 'Erstellt'),
			'updated' => Yii::t('File', 'Bearbeitet'),
			'folder_id' => Yii::t('File', 'Ordner'),
			'downloads' => Yii::t('File', 'Downloads'),
			'permission' => Yii::t('File', 'Berechtigung'),
			'file_data' => Yii::t('File', 'Datei'),
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('filename',$this->filename);
		$criteria->compare('description',$this->description,true);
		$criteria->compare('created',$this->created,true);
		$criteria->compare('updated',$this->updated,true);
		$criteria->compare('folder_id',$this->folder_id);
		$criteria->compare('downloads',$this->downloads);
		$criteria->compare('permission',$this->permission);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
}

controllers/FileController.php
<?php

/**
 * File controller.
 *
 * @package File
 * @subpackage File
 */
class FileController extends Controller
{
	/**
	 * Default view layout.
	 *
	 * @access public
	 * @var string
	 */
	public $layout = '//layouts/admin';
	
	/**
	 * Controller filters.
	 *
	 * @access public
	 * @return array
	 */
	public function filters()
	{
		return array(
			'accessControl',
		);
	}
	
	/**
	 * Controller access rules. Used by the accessControl filter.
	 *
	 * @access public
	 * @return array
	 */
	public function accessRules()
	{
		return array(
			array('allow',
				'actions' => array('view', 'create', 'upload', 'update', 'delete'),
				'roles' => array(User::LEVEL_MEMBER),
			),
			array('deny',
				'users'=>array('*'),
			),
		);
	}
	
	/**
	 * Display a file.
	 *
	 * @param integer $id File ID
	 *
	 * @access public
	 * @return void
	 */
	public function actionView($id)
	{
		$model = File::model()->findByPk($id);
		
		if (is_null($model))
			throw new CHttpException(404);
		
		if (is_null($model->theFolder->id)) {
			Yii::app()->user->setFlash('error', Yii::t('File', 'Der Ordner wurde gelöscht. Bitte wende dich an einen Administrator'));
			throw new CHttpException(404);
		}
		
		$this->render('view', array(
			'model' => $model,
		));
	}
	
	/**
	 * Upload a new file via form model.
	 *
	 * @param integer $parent Parent folder ID (Default: 0)
	 *
	 * @access public
	 * @return void
	 */
	public function actionCreate($parent) {
		$parent = Folder::model()->findByPk($parent);
		
		if (is_null($parent))
			throw new CHttpException(404);
		
		$model = new File('create');
		$model->folder_id = $parent->id;
		
		if (isset($_POST['File'])) {
			$model->attributes = $_POST['File'];
			
			//Save file
			$model->file_data = CUploadedFile::getInstance($model, 'file_data');
			
			if (!is_null($model->file_data)) {
				$fileName = $model->generateFileName($model->file_data->extensionName);
				$path = Yii::app()->basePath.'/files/';
				$filePath = $path.$fileName;
				
				if (!file_exists($filePath)) {
					if (is_writable($path)) {
						$model->prepareFile();	
						if ($model->file_data->saveAs($filePath)) {							
							if ($model->save()) {
								Yii::app()->user->setFlash('success', Yii::t('File', 'Die Datei wurde hochgeladen.'));
								$this->redirect(array('/file/file/view', 'id' => $model->id));
							}
							else {
								Yii::app()->user->setFlash('error', Yii::t('File', 'Die Datei konnte hochgeladen aber nicht gespeichert werden.'));
								if (file_exists($filePath))
									unlink($filePath);
							}
						}
						else {
							Yii::app()->user->setFlash('error', Yii::t('File', 'Die Datei konnte nicht unter `{filepath}` gespeichert werden. Bitte wende dich an den Administrator.', array('{filepath}' => $filePath)));
						}
					}
					else {
						Yii::app()->user->setFlash('error', Yii::t('File', 'Das Verzeichnis `{path}` ist nicht beschreibbar. Bitte wende dich an den Administrator.', array('{path}' => $path)));
					}
				}
				else {
					$model->addError('file_data', Yii::t('File', 'Die Datei wurde schon einmal hochgeladen. Benutze die Suche um die Datei zu finden.'));
				}
			}
			else {
				$model->addError('file_data', Yii::t('File', 'Du musst eine Datei auswählen.'));
			}
		}
		else {
			$model->permission = $model->defaultPermission;
		}
		
		$this->render('create', array(
			'folder' => $parent,
			'model' => $model,
		));
	}
	
	/**
	 * Update file.
	 *
	 * @param integer $id File ID
	 *
	 * @access public
	 * @return void
	 */
	public function actionUpdate($id) {
		$model = File::model()->findByPk($id);
		
		if (is_null($model))
			throw new CHttpException(404);

		if (isset($_POST['File'])) {
			$model->attributes = $_POST['File'];

			if ($model->save()) {
				Yii::app()->user->setFlash('success', Yii::t('File', 'Die Datei wurde hochgeladen.'));
				$this->redirect(array('/file/file/view', 'id' => $model->id));
			}
		}
		else {
			$model->permission = $model->defaultPermission;
		}
		
		$this->render('update', array(
			'folder' => $model->theFolder,
			'model' => $model,
		));
	}
	
	/**
	 * Upload new file via ajax uploader.
	 *
	 * @param integer $parent Parent folder ID
	 *
	 * @access public
	 * @return void
	 */
	public function actionUpload($parent) {
		$folder = Folder::model()->findByPk($parent);
		
		if (!is_null($folder)) {
			$model = new File('upload');
			$model->folder_id = $folder->id;
			
			$allowedExtensions = array();
			$sizeLimit = 10485760; //10 MB
			
			$uploader = new qqFileUploader($allowedExtensions, $sizeLimit);
			$result = $uploader->handleUpload($model);
			
			if (isset($result['success']) and ($result['success'] == true)) {
				$model->prepareFile($result);
				if (!$model->save()) {
					$filename = Yii::app()->basePath.'/files/'.$model->file_hash.'.'.$model->extension;
					if (file_exists($filename))
						unlink($filename);
					
					$result = array(
						'error' => Yii::t('File', 'Die Datei konnte hochgeladen aber nicht gespeichert werden!'),
					);
				}
			}
		}
		else {
			$result = array(
				'errror' => Yii::t('File', 'Der Ordner in dem die Datei gespeichert werden soll existiert nicht!'),
			);
		}

		echo htmlspecialchars(json_encode($result), ENT_NOQUOTES);
	}
	
	/**
	 * Delete file.
	 *
	 * @param integer $id File ID
	 *
	 * @access public
	 * @return void
	 */
	public function actionDelete($id) {
		$model = File::model()->findByPk($id);
		
		if (is_null($model))
			throw new CHttpException(404);
		
		$filename = $model->fullFilename;
		$folder = Folder::model()->findByPk($model->folder_id);
		
		if ($model->delete()) {
			Yii::app()->user->setFlash('info', Yii::t('File', 'Die Datei `{filename}` wurde gelöscht.', array('{filename}' => $filename)));
			if (is_null($folder))
				$this->redirect(array('/file/folder/index'));
			else
				$this->redirect(array('/file/folder/view', 'id' => $folder->id));
		}
		else {
			throw new CHttpException(500);
		}
	}
}

views/file/_form.php
<?php $form=$this->beginWidget('EBootstrapActiveForm', array(
	'id'=>'folder-form',
	'horizontal' => true,
	'htmlOptions' => array(
		'enctype'=>'multipart/form-data',
	),
)); ?>

	<?php echo $form->errorSummary($model); ?>
	
	<?php if (!$update): ?>
		<?php echo $form->beginControlGroup($model, 'file_data'); ?>
			<?php echo $form->labelEx($model,'file_data'); ?>
			<?php echo $form->beginControls($model, 'file_data'); ?>
				<?php echo $form->fileField($model,'file_data',array('maxlength'=>100)); ?>
			<?php echo $form->endControls($model, 'file_data'); ?>
		<?php echo $form->endControlGroup($model, 'file_data'); ?>
	<?php else: ?>
		<?php echo $form->beginControlGroup($model, 'filename'); ?>
			<?php echo $form->labelEx($model,'filename'); ?>
			<?php echo $form->beginControls($model, 'filename'); ?>
				<?php echo $form->textField($model,'filename',array('maxlength'=>255, 'class' => 'span5')); ?>
			<?php echo $form->endControls($model, 'filename'); ?>
		<?php echo $form->endControlGroup($model, 'filename'); ?>
	<?php endif; ?> 
		
	<?php echo $form->beginControlGroup($model, 'description'); ?>
		<?php echo $form->labelEx($model,'description'); ?>
		<?php echo $form->beginControls($model, 'description'); ?>
			<?php echo $form->textArea($model,'description', array('class' => 'span5', 'rows' => 8)); ?>
		<?php echo $form->endControls($model, 'description'); ?>
	<?php echo $form->endControlGroup($model, 'description'); ?>

	<?php echo $form->beginControlGroup($model, 'permission'); ?>
		<?php echo $form->labelEx($model,'permission'); ?>
		<?php echo $form->beginControls($model, 'permission'); ?>
			<?php echo $form->dropDownList($model, 'permission', $model->permissions); ?>
		<?php echo $form->endControls($model, 'permission'); ?>
	<?php echo $form->endControlGroup($model, 'permission'); ?>

	<?php echo $form->beginActions(); ?>
		<?php echo EBootstrap::submitButton($model->isNewRecord ? Yii::t('Project', 'Erstellen') : Yii::t('Project', 'Speichern'), 'success', '', false, 'upload', true); ?>
	<?php echo $form->endActions(); ?>

<?php $this->endWidget(); ?>

views/file/_upload.php
<?php 
$jsFile = Yii::app()->getAssetManager()->publish(Yii::getPathOfAlias('application.modules.file.js').'/fileuploader.js');
Yii::app()->clientScript->registerScriptFile($jsFile); 

$template = '<div class="qq-uploader">' .
                  	'<div class="qq-upload-drop-area"><p>'.Yii::t('File', 'Dateien hier hin bewegen').'</p>' . 
                  		'<p>'.Yii::t('File', 'oder').'</p>' . 
                  		'<a class="qq-upload-button btn btn-info"><i class="icon icon-upload icon-white"></i> '.Yii::t('File', 'Dateien auswählen').'</a>' . 
                	'</div>' .
               		'<ul class="qq-upload-list unstyled"> ' .
               		'</ul>' .
               		'<div class="clear"></div>' .
                '</div>';

$fileTemplate = '<li class="progress progress-info progress-striped">' .
    					'<div class="qq-upload-file-inner bar">' . 
			                '<div class="pull-left">' .
			                	'<span class="qq-upload-file"></span>' .
			                '</div>' .
			                '<div class="pull-right">' . 
			                	'<span class="qq-upload-size"></span> ' .
			                	'<a class="qq-upload-cancel" href="#"></a>' .
			                	'<span class="qq-upload-failed-text">' . Yii::t('File', 'Fehler') . '</span>' . 
			                '</div>' .
			        	'</div>' .
		            '</li>';

$successMessage = '<p>'.EBootstrap::ilabel(Yii::t('File', 'Alle Dateien wurden hochgeladen'), 'info').'</p>';

Yii::app()->clientScript->registerScript('file-html5-upload', "
var numUploads = 0;
var innerWidth = $('#file-upload').width();
var uploader = new qq.FileUploader({
	template: '".$template."',
    fileTemplate: '".$fileTemplate."',
	element: document.getElementById('file-upload'),
	action: '".Yii::app()->createAbsoluteUrl('/file/file/upload', array('parent' => $folder_id))."',
	sizeLimit: 10485760, //10 MB
	onSubmit: function(id, fileName) {
		numUploads = numUploads + 1;
	},
	onProgress: function(id, fileName, loaded, total) {
		$('.qq-upload-list li:eq('+id+') .qq-upload-file-inner').css({
			'width':  Math.round((loaded/total)*innerWidth),
		});
	},
	onComplete: function(id, fileName, data) {
		numUploads = numUploads - 1;
		if (numUploads == 0) {
			$('#file-upload-status').html('".$successMessage."');
			
			window.setTimeout('window.location = window.location;', 3000);
		}
	},
	debug: false,
});", CClientScript::POS_READY);
?>

<div id="file-upload"></div>
<div id="file-upload-status"></div>

views/file/_view.php
<?php 
	Yii::app()->clientScript->registerScript('file-delete-confirm', '
	$("a.file-delete").live("click", function(e) {
		if (!confirm("'.Yii::t('File', 'Wollen Sie die Datei wirklich löschen?').'")) {
			e.preventDefault();
			return false;
		}
	});
	', CClientScript::POS_READY);
?>
<tr>
	<td class="file-icon"><span class="file-icon-default file-icon-<?php echo $data->extension; ?>"></span></td>
	<td class="file-toolbar">
		<a href="<?php echo $this->createUrl('/file/file/update', array('id' => $data->id)) ?>" title="<?php echo Yii::t('File', '{filename} bearbeiten', array('{filename}' => $data->fullFilename)) ?>"><i class="icon icon-pencil"></i></a>
		<a href="<?php echo $this->createUrl('/file/file/delete', array('id' => $data->id)) ?>" title="<?php echo Yii::t('File', '{filename} löschen', array('{filename}' => $data->fullFilename)) ?>" class="file-delete"><i class="icon icon-trash"></i></a>
	</td>
	<td class="file-title"><?php echo EBootstrap::link($data->fullFilename, array('/file/file/view', 'id' => $data->id)); ?></td>
</tr>

views/file/create.php
<?php
$this->breadcrumbs=array(
	Yii::t('File', 'Dateien') => array('/file/folder/index'),
	Yii::t('File', 'Datei hochladen'),
);

$this->beginWidget(
	'AdminWidget', 
	array(
		'title' => Yii::t('File', 'Datei hochladen'),
		'icon' => 'upload',
	)
);

$this->widget('FolderBreadcrumbs', array(
	'folder_id' => $folder->id,
));

$this->renderPartial('_form', array(
	'model' => $model,
	'update' => false,
));

$this->endWidget();

views/file/update.php
<?php
$this->breadcrumbs=array(
	Yii::t('Core', 'Verwaltung') => array('/admin/index'),
	Yii::t('File', 'Dateiverwaltung') => array('/file/folder/index'),
	$model->fullFilename => array('/file/file/view', 'id' => $model->id),
);
?>

<h2><?php echo Yii::t('File', 'Datei `{filename}` bearbeiten', array('{filename}' => $model->fullFilename)); ?></h2>

<?php 
$this->widget('FolderBreadcrumbs', array(
	'folder_id' => $folder->id,
));
?>

<?php 
$this->renderPartial('_form', array(
	'model' => $model,
	'update' => true,
));
?>

views/file/view.php
<?php
$this->breadcrumbs=array(
	Yii::t('File', 'Dateien') => array('/file/folder/index'),
	$model->filename,
);

$filename = (empty($model->extension)) ? $model->filename : $model->filename.'.'.$model->extension;

$this->beginWidget(
	'AdminWidget', 
	array(
		'title' => Yii::t('File', 'Datei: {filename}', array('{filename}' => $filename)),
		'buttons' => array(
			EBootstrap::ibutton(Yii::t('Folder', 'Ordner'), array('/file/folder/create', 'parent' => $model->theFolder->id), '', 'mini', false, 'plus', false, array('title' => Yii::t('Folder', 'Ordner erstellen'))),
			EBootstrap::ibutton(Yii::t('File', 'Datei'), array('/file/file/create', 'parent' => $model->theFolder->id), 'success', 'mini', false, 'upload', true, array('title' => Yii::t('File', 'Datei hochladen'))),
		),
		'icon' => 'folder-open',
	)
);

$this->widget('FolderBreadcrumbs', array(
	'folder_id' => $model->folder_id,
	'file' => $model,
));
?>

<table class="table table-stripped">
	<tbody>
		<tr>
			<td><?php echo Yii::t('File', 'Dateiname'); ?></td>
			<td><?php echo $filename; ?></td>
		</tr>
		<tr>
			<td><?php echo Yii::t('File', 'Größe'); ?></td>
			<td><?php echo $model->filesizeRead; ?></td>
		</tr>
		<?php if (!empty($model->description)): ?>
		<tr>
			<td><?php echo Yii::t('File', 'Beschreibung'); ?></td>
			<td><?php echo nl2br(strip_tags($model->description)); ?></td>
		</tr>
		<?php endif; ?>
		<tr>
			<td></td>
			<td><?php echo EBootstrap::ibutton(Yii::t('File', 'Download'), array('/file/download/download', 'id' => $model->id), '', '', false, 'download'); ?></td>
		</tr>
	</tbody>
</table>

<?php 
switch ($model->mime) {
	case 'application/pdf':
		$view = 'pdf'; break;
	case 'image/png':
	case 'image/svg+xml':
		$view = 'image'; break;
	default:
		$view = 'default'; break;
}

$this->renderPartial('formats/'.$view, array(
	'model' => $model,
));

$this->endWidget();